[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "tailwindcss-ls"]
formatter = { command = "prettier", args = ["--parser", "html"] }
auto-format = true

[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "tailwindcss-ls"]
formatter = { command = "prettier", args = ["--parser", "css"] }
auto-format = true

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]
config.includeLanguages.tailwindcss = "css"

[[language]]
name = "json"
language-servers = ["vscode-json-language-server"]
formatter = { command = "prettier", args = ["--parser", "json"] }
auto-format = true

[[language]]
name = "yaml"
language-servers = ["vscode-json-language-server"]
formatter = { command = "prettier", args = ["--parser", "json"] }
auto-format = true

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }
auto-format = true

[[language]]
name = "rust"
formatter = { command = "rustfmt", args = ["+nightly"] }
auto-format = true
roots = ["Cargo.toml", "Cargo.lock"]

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
check = { command = "clippy" }
cargo = { allFeatures = true }
workspace = true

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

[[language]]
name = "ron"
file-types = ["ron"]
formatter = { command = "fmtron", args = ["--input", "-"] }
auto-format = true
language-servers = ["ron-lsp"]

[language-server.ron-lsp]
command = "ron-lsp"

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
