[[language]]
name = "rust"
language-servers = [ "rust-analyzer", "typos-lsp" ]
formatter = { command = "rustfmt" }

[[language]]
name = "zig"
language-servers = [ "zlp", "typos-lsp" ]

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "typos-lsp" ]

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "typos-lsp" ]

[[language]]
name = "json"
language-servers = [ "vscode-json-language-server", "typos-lsp" ]

[[language]]
name = "bash"
language-servers = [ "bash-language-server", "typos-lsp" ]
formatter = { command = "shfmt" }

[[language]]
name = "cpp"
language-servers = [ "clangd", "typos-lsp" ]

[[language]]
name = "fish"
language-servers = [ "fish-lsp", "typos-lsp" ]

[[language]]
name = "typescript"
language-servers = [ "typescript-language-server", "typos-lsp" ]

[[language]]
name = "kotlin"
language-servers = [ "kotlin-language-server", "typos-lsp" ]

[[language]]
name = "odin"
language-servers = [ "odinls", "typos-lsp" ]

[[language]]
name = "lua"
language-servers = [ "lua-language-server", "typos-lsp" ]

[[language]]
name = "dockerfile"
language-servers = [ "dockerfile-language-server", "typos-lsp" ]

[[language]]
name = "go"
language-servers = [ "gopls", "typos-lsp" ]
formatter = { command = "gofmt" }
