[ -e "$XDG_CONFIG_HOME" ] || mkdir -p "$XDG_CONFIG_HOME"
ZDOTDIR="${ZDOTDIR:-${XDG_CONFIG_HOME/zsh:-$HOME}}"
[ -e "$ZDOTDIR" ] || mkdir -p "$ZDOTDIR"

function generate_zfile() {
    local output_filename="$1"
    local output_filename_clean="$output_filename"
    [[ "$output_filename" =~ ^\. ]] && output_filename_clean="${output_filename:1}"
    local output_filepath="$ZDOTDIR/$output_filename"
    local root_path="$PWD/$PROJECT__module_folder_name/zsh/$output_filename_clean"
    increase_indent
    indent_echo "generating $output_filename_clean file ($output_filepath)"
    [[ -e "$output_filepath" ]] && mv "$output_filepath" "$output_filepath.bak"
    echo "# this $output_filename file was generated by the ${PROJECT__name:?project name not found} zsh module installer" > "$output_filepath"
    for input_filepath in "$root_path"/[0-9][0-9]-*\.sh; do
        local input_filename="$(basename -- "$input_filepath")"
        indent_echo "- adding $input_filename ($input_filepath)"
        echo "" >> "$output_filepath"
        echo "# $input_filename" >> "$output_filepath"
        echo "" >> "$output_filepath"
        cat "$input_filepath" >> "$output_filepath"
    done
    decrease_indent
}

generate_zfile zprofile
generate_zfile zshrc
generate_zfile zshenv

if [[ "$ZDOTDIR" != "$HOME" ]]; then
    [[ -L "$HOME/.zshenv" ]] && rm "$HOME/.zshenv"
    [[ -e "$HOME/.zshenv" ]] && mv "$HOME/.zshenv" "$HOME/.zshenv.bak"
    ln -s "$ZDOTDIR/.zshenv" "$HOME/.zshenv"
fi
