XDG_CONFIG_HOME="$XDG_CONFIG_HOME:-$HOME/.config"
[ -e "$XDG_CONFIG_HOME" ] || mkdir -p "$XDG_CONFIG_HOME"
ZDOTDIR="${ZDOTDIR:-${XDG_CONFIG_HOME/zsh}}"
[ -e "$ZDOTDIR" ] || mkdir -p "$ZDOTDIR"

function generate_zfile() {
    local output_filename="$1"
    local output_filename_clean="$output_filename"
    if [[ "$output_filename" =~ ^\. ]]; then
        output_filename_clean="${output_filename:1}"
    else
        output_filename=".$output_filename"
    fi
    local output_filepath="$ZDOTDIR/$output_filename"
    local root_path="$PWD/$module_folder_name/zsh/$output_filename_clean"
    indent_echo "generating $output_filename_clean file ($output_filepath)"
    [[ -e "$output_filepath" ]] && mv "$output_filepath" "$output_filepath.bak"
    echo "# this $output_filename file was generated by the $project_name_versioned zsh module installer" > "$output_filepath"
    echo "" >> "$output_filepath"
    for input_filepath in "$root_path"/[0-9][0-9]-*\.sh; do
        local input_filename="$(basename -- "$input_filepath")"
        indent_echo "- include $input_filename ($input_filepath)"
        echo "# $input_filename" >> "$output_filepath"
        echo "" >> "$output_filepath"
        cat "$input_filepath" >> "$output_filepath"
        echo "" >> "$output_filepath"
    done
    echo "# this ends the $output_filename generated by the $project_name_versioned zsh module installer" >> "$output_filepath"
    echo "# anything below this point is probably added by installers etc." >> "$output_filepath"
}

generate_zfile zprofile
generate_zfile zshrc
generate_zfile zshenv

if [[ "$ZDOTDIR" != "$HOME" ]]; then
    [[ -L "$HOME/.zshenv" ]] && rm "$HOME/.zshenv"
    [[ -f "$HOME/.zshenv" ]] && mv "$HOME/.zshenv" "$HOME/.zshenv.bak"
    ln -s "$ZDOTDIR/.zshenv" "$HOME/.zshenv"

    [[ -L "$HOME/.zprofile" ]] && rm "$HOME/.zprofile"
    [[ -f "$HOME/.zprofile" ]] && mv "$HOME/.zprofile" "$HOME/.zprofile.bak"
    ln -s "$ZDOTDIR/.zprofile" "$HOME/.zprofile"
fi
