export LANGUAGE=en_US:en
export LANG=en_US.UTF-8
export LC_LANGUAGE=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_NUMERIC=en_US.UTF-8
export LC_COLLATE=en_US.UTF-8
export LC_TIME=nb_NO.UTF-8
export LC_MESSAGES=en_US.UTF-8
export LC_MONETARY=en_US.UTF-8
export LC_ADDRESS=nb_NO.UTF-8
export LC_IDENTIFICATION=nb_NO.UTF-8
export LC_MEASUREMENT=nb_NO.UTF-8
export LC_PAPER=nb_NO.UTF-8
export LC_TELEPHONE=nb_NO.UTF-8
export LC_NAME=nb_NO.UTF-8

unset LC_ALL
export LC_ALL

export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"

export EDITOR=helix
export VISUAL=zeditor

export ZDOTDIR="${ZDOTDIR:-$XDG_CONFIG_HOME/zsh}"

export ASDF_DATA_DIR="${ASDF_DATA_DIR:-$XDG_DATA_HOME/asdf}"
export HELIX_RUNTIME_FOLDER="${HELIX_RUNTIME_FOLDER:-$XDG_DATA_HOME/helix}"

export LD_LIBRARY_PATH=/home/oasf/.local/lib/arch-mojo:$LD_LIBRARY_PATH

typeset -gU path=(
  $HOME/{,s}bin(N)
  $HOME/.local/{,s}bin(N)
  /opt/local/{,s}bin(N)
  /usr/local/{,s}bin(N)
  
  $ASDF_DATA_DIR/shims

  /usr/lib/rustup/bin
  $HOME/.cargo/bin  

  $path
)

typeset -gU fpath=(
  $ZDOTDIR/autoload
  $ZDOTDIR/functions
  $ZDOTDIR/completions

  $fpath
)

for _path in $(dir "$ZDOTDIR"/zshenv.d/*.zsh); do
  source "$_path"
done
