# uncomment for vim keybindings
# bindkey -v

autoload -Uz compinit colors

setopt sharehistory
setopt promptsubst

compinit
colors

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2

eval "$(dircolors -b)"

zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select-long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

export HISTSIZE=300000
export SAVEHIST=300000
export HISTFILE="${XDG_DATA_HOME}/zsh/histfile"
export HISTCONTROL=ignoreboth
export HISTIGNORE="&:[bf]g:c:clear:history:exit:q:pwd:* --help"

[[ -z "$PROMPT_COMMAND" ]] || PROMPT_COMMAND="history -a; $PROMPT_COMMAND"
export PROMPT_COMMAND

export LESS_TERMCAP_md="$(
  tput bold 2>/dev/null
  tput setaf 2 2>/dev/null
)"
export LESS_TERMCAP_me="$(tput sgr0 2>/dev/null)"

export ENHANCD_FILTER="fzf --height 40%:fzy"

alias neovim='nvim'
alias vim='nvim'
alias vi='nvim'
alias kakoune='kak'
alias hx='helix'

#alias open="xdg-open"
alias make="make -j$(nproc)"
alias ninja="ninja -j$(nproc)"
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias hw='hwinfo --short'
alias tarnow='tar -acf '
alias untar='tar -zxvf '
alias wget='wget -c '
alias psmem='ps auxf | sort -nr -k 4'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'

alias ls="eza --color=always --group-directories-first --icons"
alias la="eza -a --color=always --group-directories-first --icons"
alias ll="eza -la --color=always --group-directories-first --icons"
alias lt="eza -aT --color=always --group-directories-first --icons"
alias l.="eza -a --color=always --group-directories-first --icons | grep -e '^\.'"
alias ll.="eza -la --color=always --group-directories-first --icons | grep -e '^\.'"

alias jctl="journalctl -p 3 -xb"
alias jctlb="journalctl -b -1"

alias yayrm="yay -Rsn"

alias pacrm="sudo pacman -Rsn"
alias pacrmcc="sudo pacman -Scc"
alias pacunlck="sudo rm /var/lib/pacman/db.lck"
alias pacupdt="sudo pacman -Syu"
alias paccln="sudo pacman -Rsn $(pacman -Qtdq)"
alias rip="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort | tail -200 | nl"

export FZF_BASE=/usr/share/fzf

# this gets reset somewhere between here and the sourcing of .zshenv, so we add the custom ones again
typeset -gU fpath=(
  $ZDOTDIR/autoload
  $ZDOTDIR/functions
  $ZDOTDIR/completions

  $fpath
)

for _path in $(dir "$ZDOTDIR"/zshrc.d/*.zsh); do
  source "$_path"
done
